[project]
name = "example-pyproject"
version = "0.0.1"
license = "MIT"
license-files = "LICENSE.txt"
authors = { name = "Primary A", email = "pa@alaska.edu" }
maintainers = { name = "Primary A", email = "pa@alaska.edu" }
dependencies = [ "numpy", "xarray" ]